server {
    listen 3000;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass https://healthcare-rag-backend-701918629622.us-central1.run.app/api/;
        proxy_set_header Host healthcare-rag-backend-701918629622.us-central1.run.app;
        proxy_ssl_server_name on;
        proxy_http_version 1.1;
        proxy_set_header Connection '';
        proxy_buffering off;
        client_max_body_size 55M;
        proxy_read_timeout 120s;
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript;
}
